# Generated by Django 4.2.30 on 2026-05-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0002_review_alter_food_options_alter_foodtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, '待接单'), (1, '已接单'), (2, '制作中'), (3, '待上菜'), (4, '已上菜'), (5, '已取消')], default=0, verbose_name='状态'),
        ),
    ]
